{-
   Conduit API
   Conduit API documentation

   The version of the OpenAPI document: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Favorites exposing
    ( createArticleFavorite
    , deleteArticleFavorite
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



{-| Favorite an article. Auth is required
-}
createArticleFavorite : String -> Api.Request Api.Data.CreateArticle201Response
createArticleFavorite slug_path =
    Api.request
        "POST"
        "/articles/{slug}/favorite"
        [ ( "slug", identity slug_path ) ]
        []
        []
        Nothing
        Api.Data.createArticle201ResponseDecoder



{-| Unfavorite an article. Auth is required
-}
deleteArticleFavorite : String -> Api.Request Api.Data.CreateArticle201Response
deleteArticleFavorite slug_path =
    Api.request
        "DELETE"
        "/articles/{slug}/favorite"
        [ ( "slug", identity slug_path ) ]
        []
        []
        Nothing
        Api.Data.createArticle201ResponseDecoder
