{-
   Conduit API
   Conduit API documentation

   The version of the OpenAPI document: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Articles exposing
    ( createArticle
    , deleteArticle
    , getArticle
    , getArticles
    , getArticlesFeed
    , updateArticle
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



{-| Create an article. Auth is required
-}
createArticle : Api.Data.CreateArticleRequest -> Api.Request Api.Data.CreateArticle201Response
createArticle article_body =
    Api.request
        "POST"
        "/articles"
        []
        []
        []
        (Just (Api.Data.encodeCreateArticleRequest article_body))
        Api.Data.createArticle201ResponseDecoder



{-| Delete an article. Auth is required
-}
deleteArticle : String -> Api.Request ()
deleteArticle slug_path =
    Api.request
        "DELETE"
        "/articles/{slug}"
        [ ( "slug", identity slug_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())



{-| Get an article. Auth not required
-}
getArticle : String -> Api.Request Api.Data.CreateArticle201Response
getArticle slug_path =
    Api.request
        "GET"
        "/articles/{slug}"
        [ ( "slug", identity slug_path ) ]
        []
        []
        Nothing
        Api.Data.createArticle201ResponseDecoder



{-| Get most recent articles globally. Use query parameters to filter results. Auth is optional
-}
getArticles : Maybe String -> Maybe String -> Maybe String -> Maybe Int -> Maybe Int -> Api.Request Api.Data.GetArticlesFeed200Response
getArticles tag_query author_query favorited_query offset_query limit_query =
    Api.request
        "GET"
        "/articles"
        []
        [ ( "tag", Maybe.map identity tag_query ), ( "author", Maybe.map identity author_query ), ( "favorited", Maybe.map identity favorited_query ), ( "offset", Maybe.map String.fromInt offset_query ), ( "limit", Maybe.map String.fromInt limit_query ) ]
        []
        Nothing
        Api.Data.getArticlesFeed200ResponseDecoder



{-| Get most recent articles from users you follow. Use query parameters to limit. Auth is required
-}
getArticlesFeed : Maybe Int -> Maybe Int -> Api.Request Api.Data.GetArticlesFeed200Response
getArticlesFeed offset_query limit_query =
    Api.request
        "GET"
        "/articles/feed"
        []
        [ ( "offset", Maybe.map String.fromInt offset_query ), ( "limit", Maybe.map String.fromInt limit_query ) ]
        []
        Nothing
        Api.Data.getArticlesFeed200ResponseDecoder



{-| Update an article. Auth is required
-}
updateArticle : String -> Api.Data.UpdateArticleRequest -> Api.Request Api.Data.CreateArticle201Response
updateArticle slug_path article_body =
    Api.request
        "PUT"
        "/articles/{slug}"
        [ ( "slug", identity slug_path ) ]
        []
        []
        (Just (Api.Data.encodeUpdateArticleRequest article_body))
        Api.Data.createArticle201ResponseDecoder
