{-
   Conduit API
   Conduit API documentation

   The version of the OpenAPI document: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.UserAndAuthentication exposing
    ( createUser
    , getCurrentUser
    , login
    , updateCurrentUser
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



{-| Register a new user
-}
createUser : Api.Data.CreateUserRequest -> Api.Request Api.Data.Login200Response
createUser body_body =
    Api.request
        "POST"
        "/users"
        []
        []
        []
        (Just (Api.Data.encodeCreateUserRequest body_body))
        Api.Data.login200ResponseDecoder



{-| Gets the currently logged-in user
-}
getCurrentUser : Api.Request Api.Data.Login200Response
getCurrentUser =
    Api.request
        "GET"
        "/user"
        []
        []
        []
        Nothing
        Api.Data.login200ResponseDecoder



{-| Login for existing user
-}
login : Api.Data.LoginRequest -> Api.Request Api.Data.Login200Response
login body_body =
    Api.request
        "POST"
        "/users/login"
        []
        []
        []
        (Just (Api.Data.encodeLoginRequest body_body))
        Api.Data.login200ResponseDecoder



{-| Updated user information for current user
-}
updateCurrentUser : Api.Data.UpdateCurrentUserRequest -> Api.Request Api.Data.Login200Response
updateCurrentUser body_body =
    Api.request
        "PUT"
        "/user"
        []
        []
        []
        (Just (Api.Data.encodeUpdateCurrentUserRequest body_body))
        Api.Data.login200ResponseDecoder
